name: Az cli slowzyness

on:
  workflow_dispatch:

jobs:
  az:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    name: Az Cli ${{ matrix.job-index }}
    steps:      
      - name: Fake commandIndex
        run: |
          VERSION=$(cat /imagegeneration/software-report.json | jq -r '.. | objects | select(.NodeType == "ToolVersionNode" and .ToolName == "Azure CLI") | .Version')
        
          docker create --name temp-container mcr.microsoft.com/azure-cli:$VERSION
          mkdir ~/.azure
          docker cp temp-container:/root/.azure/commandIndex.json ~/.azure/commandIndex.json

      - name: Run az version
        run: az version
