name: Az cli slowzyness

on:
  workflow_dispatch:

jobs:
  az:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    name: Az Cli ${{ matrix.job-index }}
    steps:
      - name: Run az version 1st
        run: docker pull mcr.microsoft.com/azure-cli:latest
      - name: Run az version 2nd
        run: docker run mcr.microsoft.com/azure-cli:latest az version
        
