name: PR Push Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .net
        uses: Energinet-DataHub/.github/actions/setup-dotnet@lanni/actions_refactor
        with:
          global_json_directory: ${{ github.workspace }}

      - name: Build
        uses: Energinet-DataHub/.github/actions/dotnet-build-cached@lanni/actions_refactor
        with:
          solution_directory: ${{ github.workspace }}
          solution_filename: build.sln
          pull_request_number: ${{ github.event.pull_request.number }} # needs to support merge_queue
          sha: ${{ github.sha }} # needs to support merge_queue
